spring:
  application:
    name: data-jpa-test-flyway

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    datasource:
      driver-class-name: org.h2.Driver
      username: sa
      password:
      url: jdbc:h2:mem:employee

  flyway:
    location: classpath:db/migration/
    enable: true
